[project]
name = "bedrock-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inflect>=7.5.0",
]   

[dependency-groups]
dev = []
